### ISSUE TITLE
[Question] Cannot find jar files

### ISSUE THREAD

**Issue by summers314** [dandar3/android-google-firebase-common#1]
How did you find the Firebase jar files? Did you just rename .aar to .jar and place it in the /libs folder in Eclipse?

**Comment by dandar3** [comment]
No, it's a bit more complicated -  unzip the AAR, move some of the files around and then import as Android project in Eclipse. 

See these resources for a start:
- https://commonsware.com/blog/2014/07/03/consuming-aars-eclipse.html
- http://tools.android.com/tech-docs/new-build-system/aar-format
