### ISSUE TITLE
Can you please provide fIrebase-auth .jar file for version 11.0.1

### ISSUE THREAD

**Issue by suresh480** [dandar3/android-google-firebase-common#2]
Can you please provide fIrebase-auth .jar file for version 11.0.1

**Comment by dandar3** [comment]
I completelly skipped over 11.0.1 cause I couldn't see any major changes, are you ok with I'm going to make 11.0.2 available instead? thanks.

**Comment by dandar3** [comment]
See Firebase Authentication (`android-google-firebase-auth`) version 11.0.2 below - check out the videos at the end showing how you can easily download an entire project set.

https://github.com/dandar3/android-google-firebase-README/tree/11.0.2
